name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Adjust version number
        shell: "bash"
        run: |
          yq -i -o json '.version="${{ github.event.release.tag_name }}"' \
            "${{ github.workspace }}/custom_components/vantage/manifest.json"

      - name: ZIP the integration directory
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/vantage"
          zip vantage.zip -r ./

      - name: Upload the ZIP file to the release
        uses: softprops/action-gh-release@v2.1.0
        with:
          files: ${{ github.workspace }}/custom_components/vantage/vantage.zip

      - name: Github Releases To Discord
        if: github.repository == 'loopj/home-assistant-vantage'
        uses: SethCohen/github-releases-to-discord@v1.16.2
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          username: "Release Changelog"